### ISSUE TITLE
Guide for client<->bridge<->upstream configs

### ISSUE THREAD

**Issue by mahmood8664** [thehxdev/xray-install#1]
Hi, first I have to thank you for this very helpful script. I need to set up client <-> bridge <-> upstream and use DNS/CDN services like cloudflare and arvancloud to hide my server. Is there any way to add these supports into your script? or add a readme to config that?

**Comment by thehxdev** [comment]
Hi.
I don't use ArvanCloud's CDN and I don't have any idea how to configure it.
But the only thing I know is you should use `Websocket` for your server. for example `Vmess + WS`
