### ISSUE TITLE
Error while installing xray

### ISSUE THREAD

**Issue by irancss** [thehxdev/xray-install#2]
After running the script and choosing option 1 (setup xray) and according to your recommendation, choosing option 5 (
VMESS + TCP + TLS) I see the following error:
 install libpcre3 libpcre3-dev zlib1g-dev openssl libssl-dev Failed

operating system:
Description:    Ubuntu 20.10
Release:        20.10

**Comment by thehxdev** [comment]
I double checked the packages with Ubuntu package repository and all of them was correct.
please use Debian 11 instead of Ubuntu.

If your problem is not solved please change the packages repository and do a `apt update` then try again.
No one encountered this problem before (also me on multiple servers with Debian 11) so I assume that this problem is from your side.

**Comment by irancss** [comment]
Can u give me your linkedin account ? I want to provide more explanations

**Comment by thehxdev** [comment]
I don't have linkdin account. Share your problem here.

If you can, try install xray again then if it fails at installing dependencies again share what kind of error apt says you.

**Comment by irancss** [comment]
I checked this on 2 servers. One of them was purchased from (parspack) and the other from (lightnode).

The error in the lightnode server is as follows:

The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libpcre3-dev : Depends: libc6-dev but it is not going to be installed
                Depends: libpcre3 (= 2:8.39-12ubuntu0.1) but 2:8.39-13 is to be installed
 libssl-dev : Depends: libssl1.1 (= 1.1.1f-1ubuntu2.16) but 1.1.1f-1ubuntu4 is to be installed
 zlib1g-dev : Depends: zlib1g (= 1:1.2.11.dfsg-2ubuntu1.5) but 1:1.2.11.dfsg-2ubuntu4 is to be installed
              Depends: libc6-dev but it is not going to be installed or
                       libc-dev

E: Unable to correct problems, you have broken packages.
[ERROR] install libpcre3 libpcre3-dev zlib1g-dev openssl libssl-dev Failed


The error in the parspack server is as follows:

IMPORTANT NOTES:
  - The following errors were reported by the server:

    Domain: test.sample.com
    Type: connection
    Detail: xxx.xxx.xxx.xxx: Fetching
    http://test.sample.com/.well-known/acme-challenge/rXx2hZIH_SIro3jVgfbiR2liATw852BHme_wy4rCx7s:
    Timeout during connection (likely firewall problem)

    To fix these errors, please make sure that your domain name was
    entered correctly and the DNS A/AAAA record(s) for that domain
    contain(s) the right IP address. Additionally, please check that
    your computer has a publicly routable IP address and that no
    firewalls are preventing the server from communicating with the
    client. If you're using the webroot plugin, you should also verify
    that you are serving files from the webroot path you provided.
[ERROR] certbot ssl certification failed

*******
In fact, the second server gives an error in the certificate stage for the domain records, but the first server does not allow the installation at all.

**Comment by thehxdev** [comment]
In first server do a `apt install libc6-dev` then try again. If it not solved try to change VPS operating system to Debian 11.

On second server which is in Iran, I don't have any idea because multiple things can make an error.
Make sure that you have set DNS A/AAAA records correctly.
It's better to know that you don't need SSL certificates on Iran server to make a tunnel or some thing.

**Comment by irancss** [comment]
The problem was fixed by switching to Debian 11.
Thank you
Several more questions are ready for me:
1-Is there a way to improve the upload speed in the program settings?
The upload speed is usually below 1mbps.
2- Is it possible to limit the amount of internet usage for users?

**Comment by thehxdev** [comment]
1- Maybe. I don't know. Upload speed is limited by the government I think.

2- At this time NO.
