### ISSUE TITLE
Will you impose more restrictions on users management?

### ISSUE THREAD

**Issue by irancss** [thehxdev/xray-install#3]
Thank you for the script you provided.
In the new update, you have added the user management section, which is great.
In the future, will you have a goal to provide a limit on the synchronous connection of users or a limit on the traffic of each user?
Can we hope for it in the next update and is it basically implementable?

**Comment by thehxdev** [comment]
Xray or V2ray does not have user restriction functionalities built-in. So any system that limits users access must be an extra layer on top of Xray/V2ray.
In my oponion it's hard to implement such thing. Yes we can limit users with IP addresses but IPs are dynamic and they constantly change. So I don't have any plan on this.
